### ISSUE TITLE
运行llama1.py或llama2.py文件报错 TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by llery** [1694439208/GOT-OCR-Inference#6]
环境：操作系统win10，python版本v3.10.14，llama_cpp_python库的版本v3.1.0
直接跑项目里的自带的llama1.py或llama2.py文件都会报错（guff模型文件已下载且路径正确）
比如执行python llama2.py后的错误信息如下：
![image](https://github.com/user-attachments/assets/72d7bdcc-a769-4deb-b2a3-d91427bd627d)

**Comment by 1694439208** [comment]
我看你的vscode代码全红，是不是有什么依赖缺失，全红跑起来肯定报错的

**Comment by llery** [comment]
那个红只是格式检查插件报红的，不影响的

**Comment by llery** [comment]
详细的日志：
(got) D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master>C:/ProgramData/anaconda3/envs/got/python.exe d:/XinYouProject/python/GOT-OCR2.0/GOT-OCR-2.0-master/GOT/demo/gguf_test.py
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4070 Ti SUPER, compute capability 8.9, VMM: yes
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from D:/BaiduNetdiskDownload/GOT-OCR2.0/GOT_ggufs/got_model_f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = None
llama_model_loader: - kv   3:                         general.size_label str              = 619M
llama_model_loader: - kv   4:                          qwen2.block_count u32              = 24
llama_model_loader: - kv   5:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   6:                     qwen2.embedding_length u32              = 1024
llama_model_loader: - kv   7:                  qwen2.feed_forward_length u32              = 2816
llama_model_loader: - kv   8:                 qwen2.attention.head_count u32              = 16
llama_model_loader: - kv   9:              qwen2.attention.head_count_kv u32              = 16
llama_model_loader: - kv  10:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  12:                          general.file_type u32              = 1
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,151860]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,151860]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 151643
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 151643
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type  f16:  170 tensors
llm_load_vocab: control token: 151728 '<|extra_82|>' is not marked as EOG
llm_load_vocab: control token: 151837 '<|extra_191|>' is not marked as EOG
llm_load_vocab: control token: 151707 '<|extra_61|>' is not marked as EOG
llm_load_vocab: control token: 151721 '<|extra_75|>' is not marked as EOG
llm_load_vocab: control token: 151694 '<|extra_48|>' is not marked as EOG
llm_load_vocab: control token: 151781 '<|extra_135|>' is not marked as EOG
llm_load_vocab: control token: 151743 '<|extra_97|>' is not marked as EOG
llm_load_vocab: control token: 151823 '<|extra_177|>' is not marked as EOG
llm_load_vocab: control token: 151736 '<|extra_90|>' is not marked as EOG
llm_load_vocab: control token: 151800 '<|extra_154|>' is not marked as EOG
llm_load_vocab: control token: 151754 '<|extra_108|>' is not marked as EOG
llm_load_vocab: control token: 151762 '<|extra_116|>' is not marked as EOG
llm_load_vocab: control token: 151774 '<|extra_128|>' is not marked as EOG
llm_load_vocab: control token: 151859 '<imgpad>' is not marked as EOG
llm_load_vocab: control token: 151650 '<|extra_4|>' is not marked as EOG
llm_load_vocab: control token: 151787 '<|extra_141|>' is not marked as EOG
llm_load_vocab: control token: 151656 '<|extra_10|>' is not marked as EOG
llm_load_vocab: control token: 151667 '<|extra_21|>' is not marked as EOG
llm_load_vocab: control token: 151854 '</box>' is not marked as EOG
llm_load_vocab: control token: 151671 '<|extra_25|>' is not marked as EOG
llm_load_vocab: control token: 151772 '<|extra_126|>' is not marked as EOG
llm_load_vocab: control token: 151841 '<|extra_195|>' is not marked as EOG
llm_load_vocab: control token: 151724 '<|extra_78|>' is not marked as EOG
llm_load_vocab: control token: 151766 '<|extra_120|>' is not marked as EOG
llm_load_vocab: control token: 151651 '<|extra_5|>' is not marked as EOG
llm_load_vocab: control token: 151819 '<|extra_173|>' is not marked as EOG
llm_load_vocab: control token: 151692 '<|extra_46|>' is not marked as EOG
llm_load_vocab: control token: 151763 '<|extra_117|>' is not marked as EOG
llm_load_vocab: control token: 151744 '<|extra_98|>' is not marked as EOG
llm_load_vocab: control token: 151760 '<|extra_114|>' is not marked as EOG
llm_load_vocab: control token: 151849 '<|extra_203|>' is not marked as EOG
llm_load_vocab: control token: 151713 '<|extra_67|>' is not marked as EOG
llm_load_vocab: control token: 151742 '<|extra_96|>' is not marked as EOG
llm_load_vocab: control token: 151824 '<|extra_178|>' is not marked as EOG
llm_load_vocab: control token: 151646 '<|extra_0|>' is not marked as EOG
llm_load_vocab: control token: 151676 '<|extra_30|>' is not marked as EOG
llm_load_vocab: control token: 151737 '<|extra_91|>' is not marked as EOG
llm_load_vocab: control token: 151711 '<|extra_65|>' is not marked as EOG
llm_load_vocab: control token: 151785 '<|extra_139|>' is not marked as EOG
llm_load_vocab: control token: 151731 '<|extra_85|>' is not marked as EOG
llm_load_vocab: control token: 151691 '<|extra_45|>' is not marked as EOG
llm_load_vocab: control token: 151668 '<|extra_22|>' is not marked as EOG
llm_load_vocab: control token: 151789 '<|extra_143|>' is not marked as EOG
llm_load_vocab: control token: 151757 '<|extra_111|>' is not marked as EOG
llm_load_vocab: control token: 151726 '<|extra_80|>' is not marked as EOG
llm_load_vocab: control token: 151767 '<|extra_121|>' is not marked as EOG
llm_load_vocab: control token: 151714 '<|extra_68|>' is not marked as EOG
llm_load_vocab: control token: 151797 '<|extra_151|>' is not marked as EOG
llm_load_vocab: control token: 151755 '<|extra_109|>' is not marked as EOG
llm_load_vocab: control token: 151827 '<|extra_181|>' is not marked as EOG
llm_load_vocab: control token: 151665 '<|extra_19|>' is not marked as EOG
llm_load_vocab: control token: 151670 '<|extra_24|>' is not marked as EOG
llm_load_vocab: control token: 151846 '<|extra_200|>' is not marked as EOG
llm_load_vocab: control token: 151825 '<|extra_179|>' is not marked as EOG
llm_load_vocab: control token: 151695 '<|extra_49|>' is not marked as EOG
llm_load_vocab: control token: 151729 '<|extra_83|>' is not marked as EOG
llm_load_vocab: control token: 151690 '<|extra_44|>' is not marked as EOG
llm_load_vocab: control token: 151818 '<|extra_172|>' is not marked as EOG
llm_load_vocab: control token: 151677 '<|extra_31|>' is not marked as EOG
llm_load_vocab: control token: 151851 '<ref>' is not marked as EOG
llm_load_vocab: control token: 151771 '<|extra_125|>' is not marked as EOG
llm_load_vocab: control token: 151661 '<|extra_15|>' is not marked as EOG
llm_load_vocab: control token: 151822 '<|extra_176|>' is not marked as EOG
llm_load_vocab: control token: 151674 '<|extra_28|>' is not marked as EOG
llm_load_vocab: control token: 151681 '<|extra_35|>' is not marked as EOG
llm_load_vocab: control token: 151751 '<|extra_105|>' is not marked as EOG
llm_load_vocab: control token: 151845 '<|extra_199|>' is not marked as EOG
llm_load_vocab: control token: 151748 '<|extra_102|>' is not marked as EOG
llm_load_vocab: control token: 151753 '<|extra_107|>' is not marked as EOG
llm_load_vocab: control token: 151852 '</ref>' is not marked as EOG
llm_load_vocab: control token: 151786 '<|extra_140|>' is not marked as EOG
llm_load_vocab: control token: 151745 '<|extra_99|>' is not marked as EOG
llm_load_vocab: control token: 151683 '<|extra_37|>' is not marked as EOG
llm_load_vocab: control token: 151835 '<|extra_189|>' is not marked as EOG
llm_load_vocab: control token: 151696 '<|extra_50|>' is not marked as EOG
llm_load_vocab: control token: 151850 '<|extra_204|>' is not marked as EOG
llm_load_vocab: control token: 151746 '<|extra_100|>' is not marked as EOG
llm_load_vocab: control token: 151697 '<|extra_51|>' is not marked as EOG
llm_load_vocab: control token: 151700 '<|extra_54|>' is not marked as EOG
llm_load_vocab: control token: 151709 '<|extra_63|>' is not marked as EOG
llm_load_vocab: control token: 151802 '<|extra_156|>' is not marked as EOG
llm_load_vocab: control token: 151698 '<|extra_52|>' is not marked as EOG
llm_load_vocab: control token: 151794 '<|extra_148|>' is not marked as EOG
llm_load_vocab: control token: 151708 '<|extra_62|>' is not marked as EOG
llm_load_vocab: control token: 151663 '<|extra_17|>' is not marked as EOG
llm_load_vocab: control token: 151814 '<|extra_168|>' is not marked as EOG
llm_load_vocab: control token: 151792 '<|extra_146|>' is not marked as EOG
llm_load_vocab: control token: 151664 '<|extra_18|>' is not marked as EOG
llm_load_vocab: control token: 151777 '<|extra_131|>' is not marked as EOG
llm_load_vocab: control token: 151712 '<|extra_66|>' is not marked as EOG
llm_load_vocab: control token: 151644 '<|im_start|>' is not marked as EOG
llm_load_vocab: control token: 151647 '<|extra_1|>' is not marked as EOG
llm_load_vocab: control token: 151648 '<|extra_2|>' is not marked as EOG
llm_load_vocab: control token: 151649 '<|extra_3|>' is not marked as EOG
llm_load_vocab: control token: 151652 '<|extra_6|>' is not marked as EOG
llm_load_vocab: control token: 151653 '<|extra_7|>' is not marked as EOG
llm_load_vocab: control token: 151654 '<|extra_8|>' is not marked as EOG
llm_load_vocab: control token: 151655 '<|extra_9|>' is not marked as EOG
llm_load_vocab: control token: 151657 '<|extra_11|>' is not marked as EOG
llm_load_vocab: control token: 151658 '<|extra_12|>' is not marked as EOG
llm_load_vocab: control token: 151659 '<|extra_13|>' is not marked as EOG
llm_load_vocab: control token: 151660 '<|extra_14|>' is not marked as EOG
llm_load_vocab: control token: 151662 '<|extra_16|>' is not marked as EOG
llm_load_vocab: control token: 151666 '<|extra_20|>' is not marked as EOG
llm_load_vocab: control token: 151669 '<|extra_23|>' is not marked as EOG
llm_load_vocab: control token: 151672 '<|extra_26|>' is not marked as EOG
llm_load_vocab: control token: 151673 '<|extra_27|>' is not marked as EOG
llm_load_vocab: control token: 151675 '<|extra_29|>' is not marked as EOG
llm_load_vocab: control token: 151678 '<|extra_32|>' is not marked as EOG
llm_load_vocab: control token: 151679 '<|extra_33|>' is not marked as EOG
llm_load_vocab: control token: 151680 '<|extra_34|>' is not marked as EOG
llm_load_vocab: control token: 151682 '<|extra_36|>' is not marked as EOG
llm_load_vocab: control token: 151684 '<|extra_38|>' is not marked as EOG
llm_load_vocab: control token: 151685 '<|extra_39|>' is not marked as EOG
llm_load_vocab: control token: 151686 '<|extra_40|>' is not marked as EOG
llm_load_vocab: control token: 151687 '<|extra_41|>' is not marked as EOG
llm_load_vocab: control token: 151688 '<|extra_42|>' is not marked as EOG
llm_load_vocab: control token: 151689 '<|extra_43|>' is not marked as EOG
llm_load_vocab: control token: 151693 '<|extra_47|>' is not marked as EOG
llm_load_vocab: control token: 151699 '<|extra_53|>' is not marked as EOG
llm_load_vocab: control token: 151701 '<|extra_55|>' is not marked as EOG
llm_load_vocab: control token: 151702 '<|extra_56|>' is not marked as EOG
llm_load_vocab: control token: 151703 '<|extra_57|>' is not marked as EOG
llm_load_vocab: control token: 151704 '<|extra_58|>' is not marked as EOG
llm_load_vocab: control token: 151705 '<|extra_59|>' is not marked as EOG
llm_load_vocab: control token: 151706 '<|extra_60|>' is not marked as EOG
llm_load_vocab: control token: 151710 '<|extra_64|>' is not marked as EOG
llm_load_vocab: control token: 151715 '<|extra_69|>' is not marked as EOG
llm_load_vocab: control token: 151716 '<|extra_70|>' is not marked as EOG
llm_load_vocab: control token: 151717 '<|extra_71|>' is not marked as EOG
llm_load_vocab: control token: 151718 '<|extra_72|>' is not marked as EOG
llm_load_vocab: control token: 151719 '<|extra_73|>' is not marked as EOG
llm_load_vocab: control token: 151720 '<|extra_74|>' is not marked as EOG
llm_load_vocab: control token: 151722 '<|extra_76|>' is not marked as EOG
llm_load_vocab: control token: 151723 '<|extra_77|>' is not marked as EOG
llm_load_vocab: control token: 151725 '<|extra_79|>' is not marked as EOG
llm_load_vocab: control token: 151727 '<|extra_81|>' is not marked as EOG
llm_load_vocab: control token: 151730 '<|extra_84|>' is not marked as EOG
llm_load_vocab: control token: 151732 '<|extra_86|>' is not marked as EOG
llm_load_vocab: control token: 151733 '<|extra_87|>' is not marked as EOG
llm_load_vocab: control token: 151734 '<|extra_88|>' is not marked as EOG
llm_load_vocab: control token: 151735 '<|extra_89|>' is not marked as EOG
llm_load_vocab: control token: 151738 '<|extra_92|>' is not marked as EOG
llm_load_vocab: control token: 151739 '<|extra_93|>' is not marked as EOG
llm_load_vocab: control token: 151740 '<|extra_94|>' is not marked as EOG
llm_load_vocab: control token: 151741 '<|extra_95|>' is not marked as EOG
llm_load_vocab: control token: 151747 '<|extra_101|>' is not marked as EOG
llm_load_vocab: control token: 151749 '<|extra_103|>' is not marked as EOG
llm_load_vocab: control token: 151750 '<|extra_104|>' is not marked as EOG
llm_load_vocab: control token: 151752 '<|extra_106|>' is not marked as EOG
llm_load_vocab: control token: 151756 '<|extra_110|>' is not marked as EOG
llm_load_vocab: control token: 151758 '<|extra_112|>' is not marked as EOG
llm_load_vocab: control token: 151759 '<|extra_113|>' is not marked as EOG
llm_load_vocab: control token: 151761 '<|extra_115|>' is not marked as EOG
llm_load_vocab: control token: 151764 '<|extra_118|>' is not marked as EOG
llm_load_vocab: control token: 151765 '<|extra_119|>' is not marked as EOG
llm_load_vocab: control token: 151768 '<|extra_122|>' is not marked as EOG
llm_load_vocab: control token: 151769 '<|extra_123|>' is not marked as EOG
llm_load_vocab: control token: 151770 '<|extra_124|>' is not marked as EOG
llm_load_vocab: control token: 151773 '<|extra_127|>' is not marked as EOG
llm_load_vocab: control token: 151775 '<|extra_129|>' is not marked as EOG
llm_load_vocab: control token: 151776 '<|extra_130|>' is not marked as EOG
llm_load_vocab: control token: 151778 '<|extra_132|>' is not marked as EOG
llm_load_vocab: control token: 151779 '<|extra_133|>' is not marked as EOG
llm_load_vocab: control token: 151780 '<|extra_134|>' is not marked as EOG
llm_load_vocab: control token: 151782 '<|extra_136|>' is not marked as EOG
llm_load_vocab: control token: 151783 '<|extra_137|>' is not marked as EOG
llm_load_vocab: control token: 151784 '<|extra_138|>' is not marked as EOG
llm_load_vocab: control token: 151788 '<|extra_142|>' is not marked as EOG
llm_load_vocab: control token: 151790 '<|extra_144|>' is not marked as EOG
llm_load_vocab: control token: 151791 '<|extra_145|>' is not marked as EOG
llm_load_vocab: control token: 151793 '<|extra_147|>' is not marked as EOG
llm_load_vocab: control token: 151795 '<|extra_149|>' is not marked as EOG
llm_load_vocab: control token: 151796 '<|extra_150|>' is not marked as EOG
llm_load_vocab: control token: 151798 '<|extra_152|>' is not marked as EOG
llm_load_vocab: control token: 151799 '<|extra_153|>' is not marked as EOG
llm_load_vocab: control token: 151801 '<|extra_155|>' is not marked as EOG
llm_load_vocab: control token: 151803 '<|extra_157|>' is not marked as EOG
llm_load_vocab: control token: 151804 '<|extra_158|>' is not marked as EOG
llm_load_vocab: control token: 151805 '<|extra_159|>' is not marked as EOG
llm_load_vocab: control token: 151806 '<|extra_160|>' is not marked as EOG
llm_load_vocab: control token: 151807 '<|extra_161|>' is not marked as EOG
llm_load_vocab: control token: 151808 '<|extra_162|>' is not marked as EOG
llm_load_vocab: control token: 151809 '<|extra_163|>' is not marked as EOG
llm_load_vocab: control token: 151810 '<|extra_164|>' is not marked as EOG
llm_load_vocab: control token: 151811 '<|extra_165|>' is not marked as EOG
llm_load_vocab: control token: 151812 '<|extra_166|>' is not marked as EOG
llm_load_vocab: control token: 151813 '<|extra_167|>' is not marked as EOG
llm_load_vocab: control token: 151815 '<|extra_169|>' is not marked as EOG
llm_load_vocab: control token: 151816 '<|extra_170|>' is not marked as EOG
llm_load_vocab: control token: 151817 '<|extra_171|>' is not marked as EOG
llm_load_vocab: control token: 151820 '<|extra_174|>' is not marked as EOG
llm_load_vocab: control token: 151821 '<|extra_175|>' is not marked as EOG
llm_load_vocab: control token: 151826 '<|extra_180|>' is not marked as EOG
llm_load_vocab: control token: 151828 '<|extra_182|>' is not marked as EOG
llm_load_vocab: control token: 151829 '<|extra_183|>' is not marked as EOG
llm_load_vocab: control token: 151830 '<|extra_184|>' is not marked as EOG
llm_load_vocab: control token: 151831 '<|extra_185|>' is not marked as EOG
llm_load_vocab: control token: 151832 '<|extra_186|>' is not marked as EOG
llm_load_vocab: control token: 151833 '<|extra_187|>' is not marked as EOG
llm_load_vocab: control token: 151834 '<|extra_188|>' is not marked as EOG
llm_load_vocab: control token: 151836 '<|extra_190|>' is not marked as EOG
llm_load_vocab: control token: 151838 '<|extra_192|>' is not marked as EOG
llm_load_vocab: control token: 151839 '<|extra_193|>' is not marked as EOG
llm_load_vocab: control token: 151840 '<|extra_194|>' is not marked as EOG
llm_load_vocab: control token: 151842 '<|extra_196|>' is not marked as EOG
llm_load_vocab: control token: 151843 '<|extra_197|>' is not marked as EOG
llm_load_vocab: control token: 151844 '<|extra_198|>' is not marked as EOG
llm_load_vocab: control token: 151847 '<|extra_201|>' is not marked as EOG
llm_load_vocab: control token: 151848 '<|extra_202|>' is not marked as EOG
llm_load_vocab: control token: 151853 '<box>' is not marked as EOG
llm_load_vocab: control token: 151855 '<quad>' is not marked as EOG
llm_load_vocab: control token: 151856 '</quad>' is not marked as EOG
llm_load_vocab: control token: 151857 '<img>' is not marked as EOG
llm_load_vocab: control token: 151858 '</img>' is not marked as EOG
llm_load_vocab: special tokens cache size = 217
llm_load_vocab: token to piece cache size = 0.9333 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151860
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 1024
llm_load_print_meta: n_layer          = 24
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 16
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 64
llm_load_print_meta: n_embd_head_v    = 64
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 2816
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 0.5B
llm_load_print_meta: model ftype      = F16
llm_load_print_meta: model params     = 619.41 M
llm_load_print_meta: model size       = 1.15 GiB (16.00 BPW)
llm_load_print_meta: general.name     = None
llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
llm_load_print_meta: UNK token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_print_meta: EOG token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOG token        = 151645 '<|im_end|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    0.13 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/25 layers to GPU
llm_load_tensors:        CPU buffer size =  1181.68 MiB
....................................................
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 1024
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =   192.00 MiB
llama_new_context_with_model: KV self size  =  192.00 MiB, K (f16):   96.00 MiB, V (f16):   96.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.58 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   602.70 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     8.01 MiB
llama_new_context_with_model: graph nodes  = 846
llama_new_context_with_model: graph splits = 340
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 |
Model metadata: {'general.name': 'None', 'general.architecture': 'qwen2', 'general.type': 'model', 'qwen2.block_count': '24', 'general.size_label': '619M', 'qwen2.context_length': '32768', 'qwen2.embedding_length': '1024', 'general.quantization_version': '2', 'tokenizer.ggml.bos_token_id': '151643', 'qwen2.feed_forward_length': '2816', 'qwen2.attention.head_count': '16', 'qwen2.attention.head_count_kv': '16', 'qwen2.rope.freq_base': '1000000.000000', 'qwen2.attention.layer_norm_rms_epsilon': '0.000001', 'tokenizer.ggml.eos_token_id': '151643', 'general.file_type': '1', 'tokenizer.ggml.model': 'gpt2', 'tokenizer.ggml.pre': 'qwen2', 'tokenizer.ggml.unknown_token_id': '151643'}
Using fallback chat format: llama-2
d:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\GOT\demo\gguf_test.py:27: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  tensor = torch.load('D:/XinYouProject/python/GOT-OCR-Inference/3.pt')
torch.Size([1, 288, 1024])
aa:True,n_past_p:286
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
286
Llama.generate: 285 prefix-match hit, remaining 1 prompt tokens to eval
llama_decode_internal: invalid token[0] = -1
llama_decode: failed to decode, ret = -1
Traceback (most recent call last):
  File "d:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\GOT\demo\gguf_test.py", line 52, in <module>
    for token in llm.generate(prompt):
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\llama.py", line 910, in generate
    self.eval(tokens)
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\llama.py", line 643, in eval
    self._ctx.decode(self._batch)
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\_internals.py", line 305, in decode
    raise RuntimeError(f"llama_decode returned {return_code}")
RuntimeError: llama_decode returned -1
Exception ignored in: <function Llama.__del__ at 0x00000263E9D91480>
Traceback (most recent call last):
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\llama.py", line 2202, in __del__
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\llama.py", line 2199, in close
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 584, in close
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 576, in __exit__
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 561, in __exit__
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 340, in __exit__
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\_internals.py", line 69, in close
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 584, in close
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 576, in __exit__
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 561, in __exit__
  File "C:\ProgramData\anaconda3\envs\got\lib\contextlib.py", line 449, in _exit_wrapper
  File "D:\XinYouProject\python\GOT-OCR2.0\GOT-OCR-2.0-master\llama-cpp-python\llama_cpp\_internals.py", line 63, in free_model
TypeError: 'NoneType' object is not callable

**Comment by 1694439208** [comment]
装的是cpu的llama库还是gpu

**Comment by joeqi0370** [comment]
试试把 tensor = torch.load('tensora.pt')
改为: 
tensor = torch.load('tensora.pt', map_location=torch.device('cpu'))
